
name: UniMorph

description: Universal Morphological Annotation

url: https://unimorph.github.io
baseurl: ""

avatar: https://unimorph.github.io/images/mu2.png

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
